apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: customer-registration-service
  name: customer-reg-service-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: customer-registration-service
  template: 
    metadata: 
      labels: 
        app: customer-registration-service
    spec: 
      containers: 
      - name: customer-registration-service
        image: indianinsuranceregistry.azurecr.io/customerservice:latest
        ports:
          - containerPort: 7000
        #restartPolicy: Always
        
        env: 
        #----------------------------
        - name: SPRING_DATASOURCE_URL
          valueFrom: 
            configMapKeyRef:
              name: customer-reg-service-configmap
              key: database_url
        #----------------------------
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: customer-reg-service-secrets
              key: mysql-root-username
        #----------------------------
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customer-reg-service-secrets
              key: mysql-root-password
        #----------------------------
        - name: SPRING_REDIS_HOST
          valueFrom: 
            configMapKeyRef:
              name: customer-reg-service-configmap
              key: redis_host
        #----------------------------
        - name: SPRING_REDIS_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: customer-reg-service-configmap
              key: redis_password
--- 
apiVersion: v1
kind: Service
metadata: 
  name: customer-service
spec: 
  selector: 
    app: customer-registration-service
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30008