apiVersion: v1
kind: Secret
metadata:
    name: customer-reg-service-secrets
type: Opaque
data:
    #aakash@insurance-project-mysql-server
    mysql-root-username: YWFrYXNoQGluc3VyYW5jZS1wcm9qZWN0LW15c3FsLXNlcnZlcg==
    #samual@123
    mysql-root-password: c2FtdWFsQDEyMw==
    