apiVersion: v1
kind: Secret
metadata:
    name: sales-processing-service-secrets
type: Opaque
data:
    mysql-root-username: c2F0eWFtQGluZGlhbi1pbnN1cmFuY2UtbXlzcWw=
    mysql-root-password: YXJ1bkAxMjM=